const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'../..'),api=require('../../src/v1.2/core.js'),old=require('../../history/implementation/v1.1/core.js');
const data=JSON.parse(fs.readFileSync(path.join(root,'history/data/normalized_tickets.json'))),tickets=api.normalize(data.records),types=['',...new Set(tickets.map(r=>r.ticket_type))],groups=['',...new Set(tickets.map(r=>r.group_label))],priorities=['','P1','P2','P3','P4'];
const cases=[];
for(const ticket_type of types)for(const group_label of groups)for(const priority of priorities){
 const filters={ticket_type,group_label,priority};
 // Metamorphic regression: original v1.1 applied to a priority-partitioned population.
 const expected=old.metrics(priority?tickets.filter(r=>r.priority===priority):tickets,{ticket_type,group_label});
 assert.deepEqual(api.metrics(tickets,filters),expected);cases.push({filters,status:'passed',expected});
}
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
(async()=>{const browser=await chromium.launch({executablePath:process.env.ATLAS_BROWSER||'/tmp/atlas-priority-browser/chrome-headless-shell-linux64/chrome-headless-shell',headless:true,args:['--no-sandbox']});try{
 const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[],requests=[];page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));await page.goto('file://'+path.join(root,'src/v1.2/dashboard.html'));
 assert.deepEqual(await page.locator('#priority option').allTextContents(),['Todas las prioridades','P1','P2','P3','P4']);
 for(const c of cases){for(const [id,val]of [['type',c.filters.ticket_type],['group',c.filters.group_label],['priority',c.filters.priority]])await page.selectOption('#'+id,val);
 const rendered=await page.evaluate(()=>({metrics:DashboardApp.render(),rows:[...document.querySelectorAll('#tickets tr[data-row]')].map(r=>Number(r.dataset.row)),cards:[...document.querySelectorAll('#cards .value')].map(r=>r.textContent),groups:[...document.querySelectorAll('#groups .barrow')].map(r=>[r.querySelector('span').textContent,Number(r.querySelector('strong').textContent)]),states:[...document.querySelectorAll('#states .barrow strong')].map(r=>Number(r.textContent)),ages:[...document.querySelectorAll('#ages strong')].map(r=>r.textContent),scope:document.getElementById('scope').textContent,detail:document.getElementById('detailScope').textContent,anomalies:document.querySelectorAll('#anomalies tbody tr').length}));
 const m=c.expected,fmt=x=>x===null?'—':new Intl.NumberFormat('es-ES',{maximumFractionDigits:2}).format(x);
 assert.deepEqual(rendered.metrics,m);assert.deepEqual(rendered.rows,m.backlog_source_rows);assert.deepEqual(rendered.cards,[String(m.backlog),String(m.stale_48h),String(m.unassigned),fmt(m.age_mean_days)]);assert.deepEqual(Object.fromEntries(rendered.groups),m.by_group);assert.deepEqual(rendered.states,['Nuevo','En progreso','En espera'].map(s=>m.rows.filter(r=>r.state===s).length));assert.deepEqual(rendered.ages,[fmt(m.age_median_days),fmt(m.age_max_days)]);assert.equal(rendered.anomalies,m.rows.filter(r=>r.stale_reasons.length||r.age_reasons.length).length);assert.match(rendered.scope,new RegExp(`^${m.ticket_count} de 100 tickets canónicos · 102 filas fuente$`));assert.ok(rendered.detail.endsWith(c.filters.priority||'Todas las prioridades'));
 }
 await page.selectOption('#type','INC');await page.selectOption('#group','ERP');await page.selectOption('#priority','P2');await page.click('#reset');for(const id of ['type','group','priority'])assert.equal(await page.locator('#'+id).inputValue(),'');assert.equal(await page.locator('#tickets tr[data-row]').count(),64);
 await page.screenshot({path:path.join(__dirname,'desktop.png'),fullPage:true});await page.setViewportSize({width:390,height:844});await page.selectOption('#priority','P1');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:path.join(__dirname,'mobile.png'),fullPage:true});
 assert.deepEqual(errors,[]);assert.ok(requests.every(u=>u.startsWith('file:')));
 const report={status:'passed',matrix_cases:cases.length,all_priority_regression_cases:cases.filter(c=>!c.filters.priority).length,empty_backlog_cases:cases.filter(c=>!c.expected.backlog).length,browser:await browser.version(),tests:['Core matches priority partition of historical v1.1 for all 160 combinations','UI rows, cards, groups, states, age, anomalies and scope match same population for 160 combinations','32 all-priority cases preserve v1.1 values','Reset clears three controls and restores 64 backlog tickets','390px viewport has no document overflow','No browser errors or external requests'],limitations:['FORGE metamorphic regression uses historical code; independent Excel recomputation belongs to SENTINEL'],results:cases.map(({filters,expected,status})=>({filters,status,ticket_count:expected.ticket_count,backlog:expected.backlog})),errors};fs.writeFileSync(path.join(__dirname,'execution.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify({...report,results:undefined}));
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
