const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const {chromium}=require(path.join(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES,'playwright'));
const root=path.resolve(__dirname,'..'), oracle=JSON.parse(fs.readFileSync(path.join(__dirname,'independent_expected_v1.2.json'))),out={checks:[],combinations:[],regression:[],errors:[]};
const fmt=x=>x===null?'—':new Intl.NumberFormat('es-ES',{maximumFractionDigits:2}).format(x);
function check(id,actual,expected){let result='passed',error;try{assert.deepEqual(actual,expected)}catch(e){result='failed';error=e.message;out.errors.push({id,error})}out.checks.push({id,result,actual,expected});}
async function snapshot(page){return page.evaluate(()=>{const texts=s=>[...document.querySelectorAll(s)].map(x=>x.textContent.trim()),bars=id=>Object.fromEntries([...document.querySelectorAll('#'+id+' .barrow')].map(x=>[x.querySelector('span').textContent,Number(x.querySelector('strong').textContent)]));return {scope:document.querySelector('#scope').textContent,values:texts('#cards .value'),subs:texts('#cards p'),groups:bars('groups'),states:bars('states'),ages:texts('#ages strong'),rows:[...document.querySelectorAll('#tickets tr[data-row]')].map(x=>({source_row:Number(x.dataset.row),cells:[...x.cells].map(c=>c.textContent.trim())})),anomalies:[...document.querySelectorAll('#anomalies tbody tr')].map(x=>[...x.cells].map(c=>c.textContent.trim()))};});}
function expectedDOM(m){return {scope:`${m.ticket_count} de 100 tickets canónicos · 102 filas fuente`,values:[String(m.backlog),String(m.stale_48h),String(m.unassigned),fmt(m.age_mean_days)],subs:['Nuevo · En progreso · En espera',`${m.stale_evaluable} evaluables · ${m.stale_not_evaluable} no evaluables`,`${m.no_group} sin grupo · indicador separado`,`Días · ${m.age_evaluable} evaluables · ${m.age_not_evaluable} no evaluables`],groups:m.by_group,states:m.by_state,ages:[fmt(m.age_median_days),fmt(m.age_max_days)],rows:m.rows.map(r=>({source_row:r.source_row,cells:[`${r.number} · ${r.source_row}`,r.ticket_type,r.state,r.group_label,r.assigned?'Asignado':'Sin responsable',r.opened_at??'—',r.updated_at??'—',r.age_days===null?'No evaluable':fmt(r.age_days),r.stale_48h===null?r.stale_reasons.join('; '):r.stale_48h?'Sin actualización >48h':'48h o menos']})),anomalies:m.rows.filter(r=>r.age_reasons.length||r.stale_reasons.length).map(r=>[`${r.number} · ${r.source_row}`,r.stale_reasons.join('; ')||'Evaluable',r.age_reasons.join('; ')||'Evaluable'])};}
(async()=>{const browser=await chromium.launch({executablePath:process.env.ATLAS_BROWSER||'/tmp/atlas-priority-browser/chrome-headless-shell-linux64/chrome-headless-shell',args:['--no-sandbox']}),context=await browser.newContext({viewport:{width:1440,height:1000},timezoneId:'America/Santiago'}),page=await context.newPage(),legacy=await context.newPage();let runtimeErrors=[];page.on('pageerror',e=>runtimeErrors.push(e.message));await page.goto('file://'+path.join(root,'src/v1.2/dashboard.html'));await legacy.goto('file://'+path.join(root,'history/implementation/v1.1/dashboard.html'));
check('options-priority',await page.locator('#priority option').evaluateAll(xs=>xs.map(x=>[x.value,x.textContent])),[['','Todas las prioridades'],['P1','P1'],['P2','P2'],['P3','P3'],['P4','P4']]);
for(let i=0;i<oracle.cases.length;i++){const c=oracle.cases[i],f=c.filters;await page.selectOption('#type',f.ticket_type);await page.selectOption('#group',f.group_label);await page.selectOption('#priority',f.priority);const actual=await snapshot(page),expected=expectedDOM(c.expected);check(`matrix-${i}`,actual,expected);out.combinations.push({index:i,filters:f,result:out.checks.at(-1).result});if(!f.priority){await legacy.selectOption('#type',f.ticket_type);await legacy.selectOption('#group',f.group_label);check(`regression-${i}`,actual,await snapshot(legacy));out.regression.push({filters:f,result:out.checks.at(-1).result});}}
await page.selectOption('#type','INC');await page.selectOption('#group','ERP');await page.selectOption('#priority','P1');await page.click('#reset');check('reset-controls',await page.locator('select').evaluateAll(xs=>xs.map(x=>x.value)),['','','']);check('reset-all-views',await snapshot(page),expectedDOM(oracle.cases[0].expected));await page.screenshot({path:path.join(__dirname,'desktop_v1.2.png'),fullPage:true});
// Independently specified calendar boundary and non-evaluable inputs, executed in shipped browser core.
const dateCases=[['exact48','2026-09-01 00:00:00','2026-09-29 18:00:00',false,false],['over48','2026-09-01 00:00:00','2026-09-29 17:59:59',true,false],['under48','2026-09-01 00:00:00','2026-09-29 18:00:01',false,false],['missingOpen',null,'2026-09-28 00:00:00',null,true],['missingUpdate','2026-09-01 00:00:00',null,null,false],['reversed','2026-09-10 00:00:00','2026-09-09 00:00:00',null,false],['invalidOpen','2026-02-30 00:00:00','2026-09-29 18:00:00',null,true],['futureOpen','2026-10-02 00:00:00','2026-10-02 00:00:00',null,true],['futureUpdate','2026-09-01 00:00:00','2026-10-02 00:00:00',null,false],['invalidUpdate','2026-09-01 00:00:00','not a date',null,false]];
for(const [id,o,u,stale,ageNull]of dateCases){const actual=await page.evaluate(([o,u])=>{let r=DashboardCore.evaluate({opened_at:o,updated_at:u,state:'Nuevo'});return {stale:r.stale_48h,ageNull:r.age_days===null,backlog:r.backlog};},[o,u]);check('date-'+id,actual,{stale,ageNull,backlog:true});}
await page.setViewportSize({width:390,height:844});await page.selectOption('#priority','P2');check('mobile-P2',await snapshot(page),expectedDOM(oracle.cases[2].expected));check('mobile-controls-in-viewport',await page.locator('.filters select,.filters button').evaluateAll(xs=>xs.every(x=>{let b=x.getBoundingClientRect();return b.width>0&&b.x>=0&&b.right<=innerWidth})),true);check('mobile-no-document-overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.screenshot({path:path.join(__dirname,'mobile_v1.2.png'),fullPage:true});await page.click('#reset');check('mobile-reset',await snapshot(page),expectedDOM(oracle.cases[0].expected));check('runtime-errors',runtimeErrors,[]);
await browser.close();out.summary={checks:out.checks.length,failed:out.errors.length,combinations:out.combinations.length,regressions:out.regression.length,empty_combinations:oracle.cases.filter(c=>c.expected.backlog===0).length};fs.writeFileSync(path.join(__dirname,'execution_v1.2.json'),JSON.stringify(out,null,2)+'\n');console.log(JSON.stringify(out.summary));if(out.errors.length){console.log(JSON.stringify(out.errors.slice(0,5)));process.exitCode=1;}
})().catch(e=>{console.error(e);process.exitCode=1});
