const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto'),cp=require('child_process'),http=require('http');
const root=require('path').resolve(__dirname,'..'),read=p=>fs.readFileSync(root+'/'+p),hash=b=>crypto.createHash('sha256').update(b).digest('hex'),oracle=JSON.parse(read('qa/independent_expected_v1.2.json')),checks=[];
function check(id,actual,expected){assert.deepEqual(actual,expected,id);checks.push({id,result:'passed'});}
const baseline=read('src/v1.2/dashboard.html'),html=read('docs/index.html');check('baseline-git-blob-identity',crypto.createHash('sha1').update(Buffer.concat([Buffer.from('blob '+baseline.length+'\0'),baseline])).digest('hex'),'231d019fa37fae006f9127dc70a89d095cf947ec');check('exact-baseline-bytes',html.equals(baseline),true);check('exact-working-source-bytes',html.equals(read('src/v1.2/dashboard.html')),true);
function load(bytes){const elements={},scripts=[...bytes.toString().matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g)];function elem(id){return elements[id]??=( {value:'',innerHTML:'',textContent:'',listeners:{},addEventListener(e,f){this.listeners[e]=f}});}
 for(const m of scripts)if(/id="source-data"/.test(m[1]))elem('source-data').textContent=m[2];
 const context=vm.createContext({document:{getElementById:elem},Intl,Date,console});for(const m of scripts)if(!/application\/json/.test(m[1]))vm.runInContext(m[2],context);return {context,elements,elem};}
const shipped=load(html),previous=load(baseline),json=x=>JSON.parse(JSON.stringify(x)),fmt=x=>x===null?'—':new Intl.NumberFormat('es-ES',{maximumFractionDigits:2}).format(x),numeric=['ticket_count','backlog','stale_48h','stale_evaluable','stale_not_evaluable','unassigned','no_group','age_evaluable','age_not_evaluable','age_mean_days','age_median_days','age_max_days','by_group','backlog_source_rows'];
for(let i=0;i<oracle.cases.length;i++){const c=oracle.cases[i];for(const app of [shipped,previous])for(const [id,key]of [['type','ticket_type'],['group','group_label'],['priority','priority']]){app.elem(id).value=c.filters[key];app.elem(id).listeners.change();}
 const metrics=json(shipped.context.DashboardApp.render());for(const k of numeric)check(`matrix-${i}-${k}`,k.startsWith('age_')&&k.endsWith('_days')?fmt(metrics[k]):metrics[k],k.startsWith('age_')&&k.endsWith('_days')?fmt(c.expected[k]):c.expected[k]);
 for(const id of ['scope','cards','groups','states','ages','detailScope','tickets','anomalies']){check(`matrix-${i}-baseline-DOM-${id}`,{html:shipped.elem(id).innerHTML,text:shipped.elem(id).textContent},{html:previous.elem(id).innerHTML,text:previous.elem(id).textContent});}
 const cardValues=[...shipped.elem('cards').innerHTML.matchAll(/<div class="value">([^<]*)<\/div>/g)].map(m=>m[1]);check(`matrix-${i}-oracle-card-values`,cardValues,[String(c.expected.backlog),String(c.expected.stale_48h),String(c.expected.unassigned),fmt(c.expected.age_mean_days)]);
 const rows=[...shipped.elem('tickets').innerHTML.matchAll(/<tr data-row="(\d+)"/g)].map(m=>Number(m[1]));check(`matrix-${i}-oracle-rendered-rows`,rows,c.expected.backlog_source_rows);
}
shipped.elem('type').value='INC';shipped.elem('group').value='ERP';shipped.elem('priority').value='P1';shipped.elem('reset').listeners.click();check('reset-controls',['type','group','priority'].map(x=>shipped.elem(x).value),['','','']);for(const k of numeric)check('reset-'+k,json(shipped.context.DashboardApp.render())[k],oracle.cases[0].expected[k]);
(async()=>{const server=http.createServer((req,res)=>{if(req.url==='/atlas-servicenow-dashboard-lab/'){res.setHeader('Content-Type','text/html');res.end(html);}else{res.statusCode=404;res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const response=await fetch(`http://127.0.0.1:${server.address().port}/atlas-servicenow-dashboard-lab/`);check('http-project-subpath-status',response.status,200);check('http-served-bytes',Buffer.from(await response.arrayBuffer()).equals(baseline),true);server.close();check('external-script-src',/<script[^>]*\bsrc=/.test(html.toString()),false);check('external-stylesheets',/<link[^>]*rel=["']stylesheet/.test(html.toString()),false);check('nojekyll-exists',fs.existsSync(root+'/docs/.nojekyll'),true);
fs.writeFileSync(root+'/qa/execution_v1.3.json',JSON.stringify({method:'execution: Node vm DOM stub and local HTTP; no browser layout',baseline_commit:'cbf7c25c72e9f2bf14bbe978cc70e7de36050b0e',html_sha256:hash(html),source_data_sha256:hash(Buffer.from(shipped.elem('source-data').textContent)),cases:oracle.cases.length,checks:checks.length,failed:0,results:checks},null,2)+'\n');console.log(JSON.stringify({cases:oracle.cases.length,checks:checks.length,failed:0,html_sha256:hash(html)}));})().catch(e=>{console.error(e);process.exitCode=1;});
